--1
SELECT * FROM salesman
WHERE CITY IN ('PARIS', 'ROME')

--2
SELECT * FROM salesman
WHERE CITY IN ('PARIS', 'ROME')

--3
SELECT * FROM salesman
WHERE CITY NOT IN ('PARIS', 'ROME')

--4
SELECT * FROM salesman
WHERE CUSTOMER_ID IN (3007, 3008, 3009)

--5
SELECT * FROM salesman
WHERE commission BETWEEN 0.12 AND 0.14

--6
SELECT * FROM ORDERS
WHERE (purch_amt BETWEEN 500 AND 4000)
AND
NOT purch_amt IN (948.50, 1983.43)

--7
SELECT * FROM SALESMAN
WHERE NAME LIKE '[B-K]%'

SELECT * FROM salesman WHERE name BETWEEN 'A' and 'L';

--8
SELECT * FROM SALESMAN
WHERE NAME NOT LIKE '[B-K]%'

SELECT * FROM salesman WHERE name NOT BETWEEN 'A' and 'L';

--9
SELECT * FROM SALESMAN
WHERE NAME LIKE 'B%'

--10
SELECT * FROM SALESMAN
WHERE NAME LIKE '%n'

--11
SELECT * FROM SALESMAN
WHERE NAME LIKE 'N__I%'






