--1
SELECT SUM(PURCH_AMT) FROM ORDERS 

--2
SELECT AVG(PURCH_AMT) FROM ORDERS 

--3
SELECT COUNT(DISTINCT SALESMAN) FROM ORDERS

--4
SELECT COINT(*) FROM CUSTOMERS

--5
SELECT COINT(*) FROM CUSTOMERS
WHERE GRADE IS NOT NULL 

--6
SELECT MAX(PURCH_AMT) FROM ORDERS

--7
SELECT MIN(PURCH_AMT) FROM ORDERS

--8
SELECT CITY, MAX(GRADE) FROM customer
GROUP BY CITY

--9
SELECT CUSTOMER_ID, MAX(PURCH_AMT) FROM customer
GROUP BY CUSTOMER_ID

--10
SELECT CUSTOMER_ID, ORD_DATE, MAX(PURCH_AMT) FROM customer
GROUP BY CUSTOMER_ID, ORD_DATE

--11
SELECT SALESMAN_ID, MAX(PURCH_AMT) FROM ORDERS
GROUP BY SALESMAN_ID HAVING ORD_DATE = '2012-08-17'

SELECT SALESMAN_ID, MAX(PURCH_AMT) 
FROM ORDERS
WHERE ORD_DATE = '2012-08-17'
GROUP BY SALESMAN_ID 

--12 
SELECT ORD_DATE, MAX(PURCH_AMT) 
FROM ORDERS
GROUP BY ORD_DATE 
HAVING PURCH_AMT > 2000

--13
SELECT customer_id, ORD_DATE, MAX(PURCH_AMT)
FROM ORDERS 
GROUP BY CUScustomer_id, ORD_DATE
HAVING  MAX(PURCH_AMT) BETWEEN 2000 AND 6000


--14
SELECT customer_id, ORD_DATE, MAX(PURCH_AMT)
FROM ORDERS 
GROUP BY CUScustomer_id, ORD_DATE
HAVING  MAX(PURCH_AMT) IN (2000, 3000, 5760, 6000)

--15 
SELECT customer_id, MAX(PURCH_AMT)
FROM ORDERS 
GROUP BY customer_id
HAVING  customer_id BETWEEN 3002 AND 3007

--16 
SELECT customer_id, MAX(PURCH_AMT)
FROM ORDERS 
GROUP BY customer_id
HAVING  customer_id BETWEEN 3002 AND 3007
AND  MAX(PURCH_AMT) > 1000 

--17 
SELECT salesman_id, MAX(PURCH_AMT)
FROM ORDERS 
GROUP BY salesman_id
HAVING  salesman_id BETWEEN 5003 AND 5008

--18 
SELECT COUNT(ORD_ID) FROM ORDERS 
WHERE ORD_DATE = '2012-08-17' 

--19
SELECT COUNT(*) FROM ORDERS
WHERE CITY IS NOT NULL 

--20
SELECT ORD_DATE, SALESMAN_ID, COUNT(*) FROM ORDERS 
GROUP BY ORD_DATE, SALESMAN_ID 


--21 
SELECT AVG(PRO_PRICE) FROM item_mast


--22
SELECT COUNT(*) FROM item_mast
WHERE PRO_PRICE > 350

--23
SELECT PRO_COM, AVG(PRO_PRICE) FROM ititem_mast
GROUP BY PRO_COM 

--24
SELECT SUM(DPT_ALLOTMENT)
FROM EMP_DEPARTMENT 

--25
SELECT EMP_DEPT, COUNT(*) FROM emp_details
GROUP BY EMP_DEPT 









