--1 
SELECT S.NAME, C.NAME, S.CITY 
FROM SALESMAN S 
INNER JOIN CUSTOMER C 
ON S.CITY = C.ITY 

--2 
SLEECT C.CUST_NAME, S.SALESMAN_NAME
FROM CUSTOMER C 
INNER JOIN SALESMAN S
ON C.SALESMAN_ID = S.SALESMAN_ID

